export const creativeStyles = {
    Persuasion: [
        { id: 'concealed',    name: 'Concealed',    tagline: 'Elegant persuasion, concealed force',                     sentence: 'declarative', size: 'punchy' },
        { id: 'earned',       name: 'Earned',       tagline: 'Surgical brevity, every syllable earns its place',        sentence: 'fragment',    size: 'micro'  },
        { id: 'conviction',   name: 'Conviction',   tagline: 'Urgent conviction, ink that demands action',              sentence: 'imperative',  size: 'full'   },
        { id: 'velvet',       name: 'Velvet',       tagline: 'Soft power wrapped in silk, persuades before you notice', sentence: 'conditional', size: 'punchy' },
        { id: 'inevitable',   name: 'Inevitable',   tagline: 'Logic so clean the conclusion feels predestined',         sentence: 'periodic',    size: 'full'   },
        { id: 'whisper',      name: 'Whisper',      tagline: 'Quiet intensity that echoes louder than shouting',        sentence: 'litotes',     size: 'punchy' },
        { id: 'testimonial',  name: 'Testimonial',  tagline: 'First-person truth that converts doubt into belief',      sentence: 'declarative', size: 'full'   },
        { id: 'challenger',   name: 'Challenger',   tagline: 'Questions everything you thought was settled',            sentence: 'interrogative',    size: 'punchy' },
        { id: 'anchor',       name: 'Anchor',       tagline: 'Plants one idea so deep everything orbits it',            sentence: 'declarative', size: 'punchy' },
        { id: 'mirroring',    name: 'Mirroring',    tagline: 'Reflects back what the reader already feels',             sentence: 'analogy',     size: 'full'   },
        { id: 'allegory',     name: 'Allegory',     tagline: 'The whole argument smuggled inside a metaphor',           sentence: 'analogy',     size: 'extended'},
    ],
    Lyrical: [
        { id: 'soft-focus',   name: 'Soft Focus',   tagline: 'Dreamlike imagery, soft boundaries between ideas',        sentence: 'analogy',     size: 'full'   },
        { id: 'patient',      name: 'Patient',      tagline: 'Patient beauty, growth in unseen hours',                  sentence: 'periodic',    size: 'full'   },
        { id: 'slow-burn',    name: 'Slow Burn',    tagline: 'Slow-burning intensity, warmth that never fully cools',   sentence: 'paradox',     size: 'punchy' },
        { id: 'melodic',      name: 'Melodic',      tagline: 'Words that sing even without a melody',                   sentence: 'cumulative',  size: 'full'   },
        { id: 'nocturnal',    name: 'Nocturnal',    tagline: 'Late-night thoughts in twilight language',                 sentence: 'analogy',     size: 'punchy' },
        { id: 'tidal',        name: 'Tidal',        tagline: 'Build, crash, retreat — the rhythm of waves',             sentence: 'cumulative',  size: 'full'   },
        { id: 'lullaby',      name: 'Lullaby',      tagline: 'Gentle repetition that soothes and lingers',              sentence: 'anaphora',    size: 'full'   },
        { id: 'cascading',    name: 'Cascading',    tagline: 'Each phrase pours into the next, unstoppable',            sentence: 'cumulative',  size: 'full'   },
        { id: 'hymn',         name: 'Hymn',         tagline: 'Congregational beauty, meant to be shared aloud',         sentence: 'anaphora',    size: 'extended'},
        { id: 'elegy',        name: 'Elegy',        tagline: 'Beautiful mourning, grief made graceful',                 sentence: 'periodic',    size: 'extended'},
        { id: 'reflective',   name: 'Reflective',   tagline: 'The self examining the self, pen as mirror',              sentence: 'conditional', size: 'full'   },
    ],
    Raw: [
        { id: 'raw',          name: 'Raw',          tagline: 'Raw truth in plain language, no polish needed',            sentence: 'antithesis',  size: 'punchy' },
        { id: 'uncomfortable',name: 'Uncomfortable',tagline: 'Uncomfortable truths that shatter comfortable lies',      sentence: 'paradox',     size: 'punchy' },
        { id: 'infectious',   name: 'Infectious',   tagline: 'Infectious energy, words that grab you by the collar',    sentence: 'exclamatory', size: 'punchy' },
        { id: 'confessional', name: 'Confessional', tagline: 'First-person honesty with zero filter',                   sentence: 'declarative', size: 'full'   },
        { id: 'street',       name: 'Street',       tagline: 'Sidewalk philosophy in real-world vernacular',             sentence: 'fragment',    size: 'punchy' },
        { id: 'gutpunch',     name: 'Gutpunch',     tagline: 'One line that winds you, no warning given',               sentence: 'fragment',    size: 'micro'  },
        { id: 'defiant',      name: 'Defiant',      tagline: 'Words that refuse to kneel or apologize',                 sentence: 'imperative',  size: 'punchy' },
        { id: 'manifesto',    name: 'Manifesto',    tagline: 'Declaration of intent that dares you to disagree',        sentence: 'imperative',  size: 'extended'},
        { id: 'reckoning',    name: 'Reckoning',    tagline: 'Looking back at your own choices without mercy',          sentence: 'declarative', size: 'full'   },
    ],
    Craft: [
        { id: 'interlocked',  name: 'Interlocked',  tagline: 'Mechanical precision, interlocking parts, nothing wasted',sentence: 'periodic',    size: 'full'   },
        { id: 'graceful',     name: 'Graceful',     tagline: 'Graceful authority, power wrapped in courtesy',            sentence: 'conditional', size: 'punchy' },
        { id: 'transparent',  name: 'Transparent',  tagline: 'Transparent logic, structures you can see through',       sentence: 'antithesis',  size: 'full'   },
        { id: 'grandeur',     name: 'Grandeur',     tagline: 'Epic grandeur, words that echo across halls',             sentence: 'anaphora',    size: 'full'   },
        { id: 'clockwork',    name: 'Clockwork',    tagline: 'Every gear visible, every tick intentional',               sentence: 'periodic',    size: 'full'   },
        { id: 'origami',      name: 'Origami',      tagline: 'Simple folds that reveal unexpected complexity',           sentence: 'analogy',     size: 'punchy' },
        { id: 'mosaic',       name: 'Mosaic',       tagline: 'Fragments that form a complete picture together',          sentence: 'appositive',  size: 'full'   },
        { id: 'architectural',name: 'Architectural',tagline: 'Built to bear weight, form follows function',              sentence: 'declarative', size: 'full'   },
        { id: 'calligraphy',  name: 'Calligraphy',  tagline: 'Written as if the pen itself had an opinion',             sentence: 'cumulative',  size: 'full'   },
        { id: 'tapestry',     name: 'Tapestry',     tagline: 'Multiple threads woven into one seamless meaning',        sentence: 'cumulative',  size: 'extended'},
        { id: 'oulipo',       name: 'Oulipo',       tagline: 'Deliberate constraints as creative fuel, rules you invented', sentence: 'periodic', size: 'full'   },
    ],
    Wisdom: [
        { id: 'parable',      name: 'Parable',      tagline: 'Ancestral warmth, stories that teach without lecturing',  sentence: 'analogy',     size: 'full'   },
        { id: 'stoic',        name: 'Stoic',        tagline: 'Stoic repair, finds strength in what broke',              sentence: 'declarative', size: 'punchy' },
        { id: 'one-truth',    name: 'One Truth',    tagline: 'Quiet illumination, one truth at a time',                 sentence: 'analogy',     size: 'punchy' },
        { id: 'offered',      name: 'Offered',      tagline: 'Gentle authority, wisdom offered — never imposed',        sentence: 'declarative', size: 'punchy' },
        { id: 'elder',        name: 'Elder',        tagline: 'Grandparent\'s knowing, unhurried and certain',           sentence: 'conditional', size: 'full'   },
        { id: 'koan',         name: 'Koan',         tagline: 'Riddle that unlocks understanding sideways',               sentence: 'paradox',     size: 'micro'  },
        { id: 'proverb',      name: 'Proverb',      tagline: 'Folk wisdom compressed across generations',               sentence: 'chiasmus',    size: 'punchy' },
        { id: 'oracle',       name: 'Oracle',       tagline: 'Ambiguous truth that clarifies over time',                sentence: 'paradox',     size: 'punchy' },
        { id: 'philosopher',  name: 'Philosopher',  tagline: 'Rigorous inquiry — Seneca, Camus, existential depth',     sentence: 'periodic',    size: 'extended'},
    ],
    Modern: [
        { id: 'prophetic',    name: 'Prophetic',    tagline: 'Future-facing prophecy, digital-age mysticism',            sentence: 'antithesis',  size: 'full'   },
        { id: 'compressed',   name: 'Compressed',   tagline: 'Compressed fury, words that detonate on impact',          sentence: 'fragment',    size: 'micro'  },
        { id: 'still',        name: 'Still',        tagline: 'Ancient stillness in digital velocity',                   sentence: 'chiasmus',    size: 'punchy' },
        { id: 'glitch',       name: 'Glitch',       tagline: 'Beautiful errors in the system, poetic malfunction',      sentence: 'paradox',     size: 'punchy' },
        { id: 'viral',        name: 'Viral',        tagline: 'Built to spread, shareability as art form',               sentence: 'exclamatory', size: 'micro'  },
        { id: 'neon',         name: 'Neon',         tagline: 'Bright, electric, impossible to scroll past',             sentence: 'fragment',    size: 'punchy' },
        { id: 'algorithm',    name: 'Algorithm',    tagline: 'Pattern recognition turned into prose',                   sentence: 'periodic',    size: 'full'   },
        { id: 'meme',         name: 'Meme',         tagline: 'Cultural shorthand, instant recognition',                 sentence: 'fragment',    size: 'micro'  },
        { id: 'dystopian',    name: 'Dystopian',    tagline: 'Warning dressed as prediction, Black Mirror tone',        sentence: 'declarative', size: 'full'   },
    ],
    Commercial: [
        { id: 'headline',     name: 'Headline',     tagline: 'Stops the scroll, demands the read',                      sentence: 'fragment',    size: 'punchy' },
        { id: 'tagline',      name: 'Tagline',      tagline: 'Brand essence distilled into 3–7 words',                  sentence: 'fragment',    size: 'micro'  },
        { id: 'hook',         name: 'Hook',         tagline: 'The irresistible pull of the opening line',                sentence: 'interrogative',    size: 'punchy' },
        { id: 'benefit',      name: 'Benefit',      tagline: 'Features become feelings, specs become stories',           sentence: 'declarative', size: 'full'   },
        { id: 'aspirational', name: 'Aspirational', tagline: 'The life just one decision away',                          sentence: 'conditional', size: 'punchy' },
        { id: 'urgency',      name: 'Urgency',      tagline: 'Tick-tock energy, now or never',                           sentence: 'imperative',  size: 'micro'  },
        { id: 'social-proof', name: 'Social Proof', tagline: 'Everyone already knows — except you',                      sentence: 'declarative', size: 'punchy' },
        { id: 'luxury',       name: 'Luxury',       tagline: 'Premium whisper, exclusivity between the lines',           sentence: 'litotes',     size: 'punchy' },
        { id: 'unboxing',     name: 'Unboxing',     tagline: 'The excitement of what\'s inside, revealed',              sentence: 'exclamatory', size: 'punchy' },
        { id: 'micro-copy',   name: 'Micro-Copy',   tagline: 'Button text, tooltips, the invisible craft',              sentence: 'imperative',  size: 'micro'  },
        { id: 'anti-ad',      name: 'Anti-Ad',      tagline: 'Subversive honesty that sells by refusing to sell',        sentence: 'declarative', size: 'full'   },
    ],
    Warmth: [
        { id: 'toast',        name: 'Toast',        tagline: 'Raise-a-glass words for someone worth celebrating',        sentence: 'declarative', size: 'extended'},
        { id: 'blessing',     name: 'Blessing',     tagline: 'Sacred wish for another\'s journey ahead',                sentence: 'conditional', size: 'extended'},
        { id: 'comfort',      name: 'Comfort',      tagline: 'Words that sit beside you in the dark',                   sentence: 'analogy',     size: 'full'   },
        { id: 'celebration',  name: 'Celebration',  tagline: 'Joy big enough to fill every corner of the room',          sentence: 'exclamatory', size: 'full'   },
        { id: 'gratitude',    name: 'Gratitude',    tagline: 'The deepest thank-you, beyond ordinary words',             sentence: 'cumulative',  size: 'full'   },
        { id: 'nostalgia',    name: 'Nostalgia',    tagline: 'Yesterday\'s warmth carried gently into today',            sentence: 'analogy',     size: 'punchy' },
        { id: 'encouragement',name: 'Encouragement',tagline: 'Fuel for the next step, the next try',                    sentence: 'imperative',  size: 'punchy' },
        { id: 'eulogy',       name: 'Eulogy',       tagline: 'Honor what was, acknowledge what remains',                 sentence: 'periodic',    size: 'extended'},
        { id: 'vow',          name: 'Vow',          tagline: 'A promise spoken once, meant forever',                    sentence: 'declarative', size: 'extended'},
        { id: 'homecoming',   name: 'Homecoming',   tagline: 'The feeling of returning to where you belong',            sentence: 'analogy',     size: 'full'   },
        { id: 'ritual',       name: 'Ritual',       tagline: 'Tradition speaking through you — ceremony in words',       sentence: 'anaphora',    size: 'grand'  },
    ],
    Wit: [
        { id: 'deadpan',      name: 'Deadpan',      tagline: 'Flat delivery, explosive meaning underneath',             sentence: 'declarative', size: 'punchy' },
        { id: 'ironic',       name: 'Ironic',       tagline: 'Says one thing, means the beautiful opposite',             sentence: 'antithesis',  size: 'punchy' },
        { id: 'observational',name: 'Observational',tagline: 'Notices what everyone else walked past',                   sentence: 'appositive',  size: 'punchy' },
        { id: 'self-aware',   name: 'Self-Aware',   tagline: 'Winks at its own cleverness without being smug',           sentence: 'paradox',     size: 'punchy' },
        { id: 'sardonic',     name: 'Sardonic',     tagline: 'Sweetly bitter, bitterly sweet',                           sentence: 'antithesis',  size: 'punchy' },
        { id: 'absurdist',    name: 'Absurdist',    tagline: 'Logic\'s exit door is the joke\'s entrance',               sentence: 'paradox',     size: 'punchy' },
        { id: 'punchline',    name: 'Punchline',    tagline: 'Everything builds to the last word',                       sentence: 'periodic',    size: 'punchy' },
        { id: 'roast',        name: 'Roast',        tagline: 'Affectionate destruction, love disguised as fire',         sentence: 'exclamatory', size: 'punchy' },
        { id: 'caption',      name: 'Caption',      tagline: 'The words beneath the image that change everything',      sentence: 'fragment',    size: 'punchy' },
        { id: 'satirist',     name: 'Satirist',     tagline: 'Institutional critique through humor — Swift, The Onion',  sentence: 'declarative', size: 'full'   },
        { id: 'wilde',        name: 'Wilde',        tagline: 'Intellect having fun — smart humor about big questions',   sentence: 'paradox',     size: 'full'   },
    ],
    Visual: [
        { id: 'cinematic',    name: 'Cinematic',    tagline: 'Wide-angle words, camera-ready imagery',                   sentence: 'cumulative',  size: 'full'   },
        { id: 'textural',     name: 'Textural',     tagline: 'Words you can feel on your fingertips',                    sentence: 'analogy',     size: 'punchy' },
        { id: 'chromatic',    name: 'Chromatic',    tagline: 'Color as meaning, palette as narrative',                   sentence: 'appositive',  size: 'full'   },
        { id: 'silhouette',   name: 'Silhouette',   tagline: 'Defined entirely by what\'s left out',                     sentence: 'litotes',     size: 'punchy' },
        { id: 'miniature',    name: 'Miniature',    tagline: 'An entire world inside one small detail',                  sentence: 'analogy',     size: 'micro'  },
        { id: 'panoramic',    name: 'Panoramic',    tagline: 'Sweeping vista, nothing held back',                        sentence: 'cumulative',  size: 'full'   },
        { id: 'sketch',       name: 'Sketch',       tagline: 'Quick strokes that capture pure essence',                 sentence: 'fragment',    size: 'punchy' },
        { id: 'synesthesia',  name: 'Synesthesia',  tagline: 'Hear the color, taste the sound, see the music',          sentence: 'analogy',     size: 'full'   },
        { id: 'emblem',       name: 'Emblem',       tagline: 'The image IS the argument, symbol as statement',           sentence: 'analogy',     size: 'punchy' },
    ],
    Minimal: [
        { id: 'haiku',        name: 'Haiku',        tagline: 'Nature\'s breath in the briefest form',                   sentence: 'fragment',    size: 'micro'  },
        { id: 'epigram',      name: 'Epigram',      tagline: 'Sharp as a scalpel, short as a breath',                   sentence: 'antithesis',  size: 'micro'  },
        { id: 'inscription',  name: 'Inscription',  tagline: 'Carved to outlast the stone it\'s written on',            sentence: 'declarative', size: 'punchy' },
        { id: 'signal',       name: 'Signal',       tagline: 'One clear note cutting through noise',                    sentence: 'fragment',    size: 'micro'  },
        { id: 'void',         name: 'Void',         tagline: 'The silence between words does the work',                 sentence: 'litotes',     size: 'micro'  },
        { id: 'distilled',    name: 'Distilled',    tagline: 'Boiled to nothing but truth',                             sentence: 'fragment',    size: 'micro'  },
        { id: 'telegram',     name: 'Telegram',     tagline: 'Every word costs something — spend wisely',               sentence: 'fragment',    size: 'micro'  },
        { id: 'ash',          name: 'Ash',          tagline: 'What remains after everything unnecessary burns',          sentence: 'fragment',    size: 'micro'  },
    ],
    Narrative: [
        { id: 'voiceover',    name: 'Voiceover',    tagline: 'The narrator\'s voice, intimate and all-seeing',          sentence: 'declarative', size: 'extended'},
        { id: 'cliffhanger',  name: 'Cliffhanger',  tagline: 'Ends mid-air, forces the next thought',                   sentence: 'fragment',    size: 'punchy' },
        { id: 'origin',       name: 'Origin',       tagline: 'Every great thing started with this moment',              sentence: 'declarative', size: 'extended'},
        { id: 'flashback',    name: 'Flashback',    tagline: 'Present tension lit by a memory\'s glow',                 sentence: 'periodic',    size: 'extended'},
        { id: 'fable',        name: 'Fable',        tagline: 'Animals, objects, or ideas teaching human truths',         sentence: 'analogy',     size: 'extended'},
        { id: 'noir',         name: 'Noir',         tagline: 'Rain-soaked cynicism with a beating heart',               sentence: 'declarative', size: 'full'   },
        { id: 'campfire',     name: 'Campfire',     tagline: 'Spoken into firelight, meant to be retold',               sentence: 'cumulative',  size: 'extended'},
        { id: 'trailer',      name: 'Trailer',      tagline: 'The 10 words that sell the whole story',                  sentence: 'fragment',    size: 'punchy' },
        { id: 'mythic',       name: 'Mythic',       tagline: 'Hero\'s journey compressed into one line',                sentence: 'declarative', size: 'extended'},
    ],
    Sacred: [
        { id: 'mantra',       name: 'Mantra',       tagline: 'Repetition that rewires, words as meditation',            sentence: 'anaphora',    size: 'punchy' },
        { id: 'invocation',   name: 'Invocation',   tagline: 'Calling something into being with language',              sentence: 'imperative',  size: 'full'   },
        { id: 'psalm',        name: 'Psalm',        tagline: 'Song of praise, lament, or wonder',                       sentence: 'anaphora',    size: 'extended'},
        { id: 'breath',       name: 'Breath',       tagline: 'Inhale the question, exhale the knowing',                 sentence: 'paradox',     size: 'punchy' },
        { id: 'dharma',       name: 'Dharma',       tagline: 'Teaching that arrives exactly when needed',               sentence: 'conditional', size: 'full'   },
        { id: 'sanctuary',    name: 'Sanctuary',    tagline: 'Words that create a safe interior space',                 sentence: 'analogy',     size: 'full'   },
        { id: 'devotion',     name: 'Devotion',     tagline: 'Pure attention poured toward one thing',                  sentence: 'cumulative',  size: 'full'   },
    ],
    Playful: [
        { id: 'whimsy',       name: 'Whimsy',       tagline: 'Logic on holiday, imagination in charge',                 sentence: 'exclamatory', size: 'punchy' },
        { id: 'riddle',       name: 'Riddle',       tagline: 'A question wearing a clever disguise',                    sentence: 'interrogative',    size: 'punchy' },
        { id: 'bounce',       name: 'Bounce',       tagline: 'Words that skip, hop, and refuse to sit still',           sentence: 'exclamatory', size: 'punchy' },
        { id: 'limelight',    name: 'Limelight',    tagline: 'Theatrical flair, every word takes a bow',                sentence: 'exclamatory', size: 'full'   },
        { id: 'nonsense',     name: 'Nonsense',     tagline: 'Serious about being unserious',                           sentence: 'paradox',     size: 'punchy' },
        { id: 'sparkle',      name: 'Sparkle',      tagline: 'Glitter in word form, delightful and brief',              sentence: 'fragment',    size: 'micro'  },
        { id: 'storybook',    name: 'Storybook',    tagline: 'Once upon a time, but only one line',                     sentence: 'declarative', size: 'full'   },
        { id: 'inventor',     name: 'Inventor',     tagline: 'Making up words, new language — Dr. Seuss energy',        sentence: 'exclamatory', size: 'punchy' },
    ],
    Dialog: [
        { id: 'subtext',      name: 'Subtext',      tagline: 'What\'s unsaid weighs more than what\'s spoken',          sentence: 'declarative', size: 'full'   },
        { id: 'banter',       name: 'Banter',       tagline: 'Two minds fencing, rapid-fire rhythm',                    sentence: 'antithesis',  size: 'punchy' },
        { id: 'monologue',    name: 'Monologue',    tagline: 'One voice holding the room, earning every second',        sentence: 'cumulative',  size: 'grand'  },
        { id: 'one-liner',    name: 'One-Liner',    tagline: 'The exit line that echoes after the door shuts',           sentence: 'fragment',    size: 'punchy' },
        { id: 'retort',       name: 'Retort',       tagline: 'The comeback that arrives perfectly on time',              sentence: 'antithesis',  size: 'punchy' },
        { id: 'confession-d', name: 'Confession',   tagline: 'The crack in the armor where truth finally spills',       sentence: 'declarative', size: 'extended'},
        { id: 'threat',       name: 'Threat',       tagline: 'Menace folded into courtesy, power through restraint',     sentence: 'conditional', size: 'full'   },
        { id: 'farewell',     name: 'Farewell',     tagline: 'Last words before the scene cuts to black',               sentence: 'declarative', size: 'full'   },
        { id: 'socratic',     name: 'Socratic',     tagline: 'Questions that teach by cornering — two minds excavating', sentence: 'interrogative',    size: 'extended'},
    ],
};

export const moods = [
    { id: 'neutral',    name: 'Neutral'    },
    { id: 'warm',       name: 'Warm'       },
    { id: 'sharp',      name: 'Sharp'      },
    { id: 'playful',    name: 'Playful'    },
    { id: 'dark',       name: 'Dark'       },
    { id: 'bold',       name: 'Bold'       },
    { id: 'poetic',     name: 'Poetic'     },
    { id: 'calm',       name: 'Calm'       },
    { id: 'energetic',  name: 'Energetic'  },
    { id: 'elegant',    name: 'Elegant'    },
    { id: 'inspiring',  name: 'Inspiring'  },
    { id: 'minimal',    name: 'Minimal'    },
    { id: 'mysterious', name: 'Mysterious' },
    { id: 'rebellious', name: 'Rebellious' },
    { id: 'nostalgic',  name: 'Nostalgic'  },
    { id: 'raw',        name: 'Raw'        },
];

export const tones = [
    { id: '',              name: 'Auto'           },
    { id: 'conversational',name: 'Conversational' },
    { id: 'authoritative', name: 'Authoritative'  },
    { id: 'witty',         name: 'Witty'          },
    { id: 'dry',           name: 'Dry'            },
    { id: 'philosophical', name: 'Philosophical'  },
    { id: 'cinematic',     name: 'Cinematic'      },
    { id: 'tender',        name: 'Tender'         },
    { id: 'provocative',   name: 'Provocative'    },
    { id: 'formal',        name: 'Formal'         },
    { id: 'candid',        name: 'Candid'         },
    { id: 'optimistic',    name: 'Optimistic'     },
    { id: 'flowing',       name: 'Flowing'        },
    { id: 'concise',       name: 'Concise'        },
    { id: 'vivid',         name: 'Vivid'          },
    { id: 'serene',        name: 'Serene'         },
];

export const sizes = [
    { id: 'micro',    name: 'Micro',    label: '3–5w'   },
    { id: 'punchy',   name: 'Punchy',   label: '5–8w'   },
    { id: 'full',     name: 'Full',     label: '8–12w'  },
    { id: 'extended', name: 'Extended', label: '12–18w' },
    { id: 'grand',    name: 'Grand',    label: '18–25w' },
];

export const howCloseOptions = [
    { id: 'literal',    name: 'Literal',    desc: 'Stay close to the input words' },
    { id: 'interpret',  name: 'Interpret',  desc: 'Use input as theme, allow metaphor' },
    { id: 'leap',       name: 'Leap',       desc: 'Use input as springboard, surprise welcome' },
];

export const sentenceStyles = [
    { id: 'auto',         name: 'Auto'         },
    { id: 'declarative',  name: 'Declarative'  },
    { id: 'exclamatory',  name: 'Exclamatory'  },
    { id: 'interrogative',name: 'Question'     },
    { id: 'imperative',   name: 'Imperative'   },
    { id: 'conditional',  name: 'Conditional'  },
    { id: 'paradox',      name: 'Paradox'      },
    { id: 'antithesis',   name: 'Antithesis'   },
    { id: 'chiasmus',     name: 'Chiasmus'     },
    { id: 'analogy',      name: 'Analogy'      },
    { id: 'appositive',   name: 'Appositive'   },
    { id: 'fragment',     name: 'Fragment'     },
    { id: 'cumulative',   name: 'Cumulative'   },
    { id: 'periodic',     name: 'Periodic'     },
    { id: 'anaphora',     name: 'Anaphora'     },
    { id: 'litotes',      name: 'Litotes'      },
    { id: 'fivewh',      name: '5WH'         },
];

export const personas = [
    { id: 'copywriter',       name: 'Copywriter',         tagline: 'Headlines that stop, lines that sell',            category: 'Commercial',     defaults: { size: 'punchy',   sentence: 'fragment',    mood: 'sharp'   } },
    { id: 'slogan_writer',    name: 'Slogan Writer',      tagline: 'Brand identity compressed into words',            category: 'Commercial',     defaults: { size: 'micro',    sentence: 'fragment',    mood: 'neutral' } },
    { id: 'brand_voice',      name: 'Brand Voice Writer', tagline: 'The tone that defines an entire brand',           category: 'Commercial',     defaults: { size: 'punchy',   sentence: 'declarative', mood: 'neutral' } },
    { id: 'lyricist',         name: 'Lyricist',           tagline: 'Hook that won\'t leave your head',                category: 'Word Artist',    defaults: { size: 'full',     sentence: 'anaphora',    mood: 'warm'    } },
    { id: 'poet',             name: 'Poet',               tagline: 'A line that echoes long after reading',           category: 'Word Artist',    defaults: { size: 'full',     sentence: 'analogy',     mood: 'neutral' } },
    { id: 'dialog_writer',    name: 'Dialog Writer',      tagline: 'The iconic line that defines a character',        category: 'Entertainment',  defaults: { size: 'punchy',   sentence: 'declarative', mood: 'sharp'   } },
    { id: 'comedian',         name: 'Stand-up Comedian',  tagline: 'Setup, misdirect, land — the laugh craft',       category: 'Entertainment',  defaults: { size: 'full',     sentence: 'declarative', mood: 'playful' } },
    { id: 'trailer_writer',   name: 'Trailer Line Writer',tagline: 'The words that sell the whole story',             category: 'Entertainment',  defaults: { size: 'punchy',   sentence: 'fragment',    mood: 'sharp'   } },
    { id: 'speech_writer',    name: 'Speech Writer',      tagline: 'The quotable line that moves rooms',              category: 'Professional',   defaults: { size: 'extended', sentence: 'anaphora',    mood: 'warm'    } },
    { id: 'pitch_writer',     name: 'Pitch Writer',       tagline: 'The 10-second sell that opens doors',             category: 'Professional',   defaults: { size: 'full',     sentence: 'declarative', mood: 'sharp'   } },
    { id: 'caption_writer',   name: 'Caption Writer',     tagline: 'Words that stop the scroll',                      category: 'Social',         defaults: { size: 'punchy',   sentence: 'fragment',    mood: 'playful' } },
    { id: 'bio_writer',       name: 'Bio Writer',         tagline: 'Identity distilled into 150 characters',          category: 'Social',         defaults: { size: 'punchy',   sentence: 'fragment',    mood: 'playful' } },
    { id: 'wish_writer',      name: 'Wish Writer',        tagline: 'Celebration, comfort, and blessing in a line',    category: 'Personal',       defaults: { size: 'full',     sentence: 'conditional', mood: 'warm'    } },
    { id: 'toast_writer',     name: 'Toast Writer',       tagline: 'Raise-a-glass words worth remembering',           category: 'Personal',       defaults: { size: 'extended', sentence: 'cumulative',  mood: 'warm'    } },
    { id: 'headline_writer',  name: 'Headline Writer',    tagline: 'News in a line, truth in a glance',               category: 'Journalism',     defaults: { size: 'punchy',   sentence: 'declarative', mood: 'sharp'   } },
    { id: 'ux_writer',        name: 'UX Writer',          tagline: 'Invisible words that guide and reassure',         category: 'Design',         defaults: { size: 'micro',    sentence: 'imperative',  mood: 'warm'    } },
    { id: 'tattoo_writer',    name: 'Tattoo Writer',      tagline: 'Permanent words chosen for a lifetime',           category: 'Design',         defaults: { size: 'micro',    sentence: 'fragment',    mood: 'neutral' } },
    { id: 'mentor',           name: 'Mentor / Coach',     tagline: 'The line that changes someone\'s trajectory',     category: 'Wisdom',         defaults: { size: 'punchy',   sentence: 'imperative',  mood: 'warm'    } },
    { id: 'affirmation_writer',name:'Affirmation Writer', tagline: 'Words that rewire belief from within',            category: 'Spiritual',      defaults: { size: 'punchy',   sentence: 'declarative', mood: 'warm'    } },
    { id: 'protest_writer',   name: 'Protest Sign Writer',tagline: 'Resistance and truth on cardboard',               category: 'Civic',          defaults: { size: 'punchy',   sentence: 'imperative',  mood: 'sharp'   } },
    { id: 'food_writer',      name: 'Tasting Note Writer',tagline: 'Flavor translated into words',                    category: 'Niche',          defaults: { size: 'full',     sentence: 'cumulative',  mood: 'warm'    } },
];

export const personaCategories = ['Commercial', 'Word Artist', 'Entertainment', 'Professional', 'Social', 'Personal', 'Journalism', 'Design', 'Wisdom', 'Spiritual', 'Civic', 'Niche'];
